import MenuClient from "./MenuClient";

export default async function MenuPage({
  searchParams,
}: {
  searchParams: Promise<{ table?: string }>;
}) {
  const { table } = await searchParams;

  const categories = [
    { id: 1, name: "food" },
    { id: 2, name: "drinks" },
    { id: 3, name: "dessert" },
  ];

  const foodItems = [
    // Food items (8)
    {
      id: 1,
      restaurant_id: 1,
      name: "ស៊ុបម្រះ",
      description: "Hot Pot with Bitter Melon",
      price: 7.5,
      price_khr: 30000,
      image_url: "/examplemenu/soup.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 2,
      restaurant_id: 1,
      name: "ខាត់ណាទឹកភ្នែក",
      description: "Spicied Beef Salad With Kale",
      price: 5,
      price_khr: 20000,
      image_url: "/examplemenu/khatnaterkpnek.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 3,
      restaurant_id: 1,
      name: "ដំឡូងបារាំងចៀន",
      description: "French Fries",
      price: 2.5,
      price_khr: 10000,
      image_url: "/examplemenu/frenchfries.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 4,
      restaurant_id: 1,
      name: "ប្រហិតសាច់គោ",
      description: "Beef Meatball",
      price: 5,
      price_khr: 20000,
      image_url: "/examplemenu/beefmeetball.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 5,
      restaurant_id: 1,
      name: "ភ្លាបង្គាម្រះ",
      description: "Shrimp Salad With Bittermelon",
      price: 5,
      price_khr: 20000,
      image_url: "/examplemenu/plea.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 6,
      restaurant_id: 1,
      name: "បាយឡុកឡាក់សាច់គោy",
      description: "Lok Lak Rice With Tomato and Onion",
      price: 3.5,
      price_khr: 14000,
      image_url: "/examplemenu/bayloklak.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 7,
      restaurant_id: 1,
      name: "គុយទាវពិសេស",
      description: "Special Noodle Soup (Mixed Meat)",
      price: 2.5,
      price_khr: 10000,
      image_url: "/examplemenu/kuyteav.webp",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    {
      id: 8,
      restaurant_id: 1,
      name: "Hamburger",
      description: "Juicy beef patty with lettuce, tomato, and cheese",
      price: 8.49,
      price_khr: 33960,
      image_url: "/examplemenu/food8.jpg",
      category_ids: [1],
      is_available: true,
      variants: [],
    },
    // Drinks items (8)
    {
      id: 9,
      restaurant_id: 1,
      name: "Coca-Cola",
      description: "Classic Coca-Cola",
      price: 2.49,
      price_khr: 9960,
      image_url: "/examplemenu/drink1.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 10,
      restaurant_id: 1,
      name: "Orange Juice",
      description: "Freshly squeezed orange juice",
      price: 3.49,
      price_khr: 13960,
      image_url: "/examplemenu/drink2.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 11,
      restaurant_id: 1,
      name: "Iced Coffee",
      description: "Cold brewed iced coffee",
      price: 4.49,
      price_khr: 17960,
      image_url: "/examplemenu/drink3.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 12,
      restaurant_id: 1,
      name: "Green Tea",
      description: "Hot green tea",
      price: 2.99,
      price_khr: 11960,
      image_url: "/examplemenu/drink4.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 13,
      restaurant_id: 1,
      name: "កាហ្វេទឹកដោះគោទឹកកក",
      description: "Iced Coffee With Milk",
      price: 1.75,
      price_khr: 70000,
      image_url: "/examplemenu/icecoffe.webp",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 14,
      restaurant_id: 1,
      name: "ទឹកផ្លែឈឺក្រឡុក(ម្នាស់, ចេក, ត្រាវ, ប៉ោម)",
      description: "FruitShack (Avocado, Pine-apple, Banana, Taro, Apple)",
      price: 2,
      price_khr: 8000,
      image_url: "/examplemenu/fruitshack.webp",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 15,
      restaurant_id: 1,
      name: "Beer",
      description: "Cold beer",
      price: 3.99,
      price_khr: 15960,
      image_url: "/examplemenu/drink7.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    {
      id: 16,
      restaurant_id: 1,
      name: "Milkshake",
      description: "Chocolate milkshake",
      price: 4.99,
      price_khr: 19960,
      image_url: "/examplemenu/drink8.jpg",
      category_ids: [2],
      is_available: true,
      variants: [],
    },
    // Dessert items (8)
    {
      id: 17,
      restaurant_id: 1,
      name: "Chocolate Cake",
      description: "Rich chocolate cake",
      price: 5.99,
      price_khr: 23960,
      image_url: "/examplemenu/dessert1.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 18,
      restaurant_id: 1,
      name: "Ice Cream",
      description: "Vanilla ice cream with toppings",
      price: 4.49,
      price_khr: 17960,
      image_url: "/examplemenu/dessert2.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 19,
      restaurant_id: 1,
      name: "Tiramisu",
      description: "Classic Italian tiramisu",
      price: 6.49,
      price_khr: 25960,
      image_url: "/examplemenu/dessert3.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 20,
      restaurant_id: 1,
      name: "Cheesecake",
      description: "Creamy cheesecake with berry sauce",
      price: 5.99,
      price_khr: 23960,
      image_url: "/examplemenu/dessert4.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 21,
      restaurant_id: 1,
      name: "Fruit Salad",
      description: "Fresh mixed fruit salad",
      price: 4.99,
      price_khr: 19960,
      image_url: "/examplemenu/dessert5.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 22,
      restaurant_id: 1,
      name: "Pudding",
      description: "Creamy vanilla pudding",
      price: 3.99,
      price_khr: 15960,
      image_url: "/examplemenu/dessert6.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 23,
      restaurant_id: 1,
      name: "Donuts",
      description: "Assorted donuts",
      price: 3.49,
      price_khr: 13960,
      image_url: "/examplemenu/dessert7.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
    {
      id: 24,
      restaurant_id: 1,
      name: "Macarons",
      description: "Colorful French macarons",
      price: 6.99,
      price_khr: 27960,
      image_url: "/examplemenu/dessert8.jpg",
      category_ids: [3],
      is_available: true,
      variants: [],
    },
  ];

  const geofencing = { is_enabled: false, can_order: true, distance_meters: null, radius_meters: 100 };
  const restaurant = {
    id: 1,
    slug: "example-restaurant",
    name: "Example Restaurant",
    logo_url: null,
  };

  return (
    <MenuClient
      categories={categories}
      foodItems={foodItems}
      tableNumber={table || "1"}
      restaurant={restaurant}
      geofencing={geofencing}
    />
  );
}
