"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

// Define translations
export const translations = {
  en: {
    // Menu
    menu: "Menu",
    searchDishes: "Search dishes…",
    grid: "Grid",
    list: "List",
    qrCode: "QR Code",
    addDish: "Add Dish",
    yourRestaurant: "Your restaurant",
    view: "View",
    edit: "Edit",
    totalDishes: "Total Dishes",
    available: "Available",
    categories: "Categories",
    all: "All",
    createYourRestaurantProfile: "Create your restaurant profile before adding menu items.",
    createRestaurant: "Create Restaurant",
    noItemsFound: "No items found",
    items: "items",
    item: "item",
    unavailable: "Unavailable",
    photo: "Photo",
    clickToUpload: "Click to upload",
    orPasteImageUrl: "Or paste image URL…",
    name: "Name",
    dishName: "Dish name",
    category: "Category",
    describeTheDish: "Describe the dish…",
    pricing: "Pricing",
    auto: "Auto",
    autoCalculateKhr: "Auto-calculate KHR",
    rate: "rate",
    options: "Options",
    visibleOnMenu: "Visible on menu",
    plantBasedItem: "Plant-based item",
    preview: "Preview",
    itemName: "Item name…",
    noDescriptionYet: "No description yet…",
    saveItem: "Save Item",
    saving: "Saving…",
    cancel: "Cancel",
    editItem: "Edit Item",
    chooseImage: "Choose Image",
    orPasteUrl: "Or paste URL",
    pleaseChooseAnImageFile: "Please choose an image file.",
    couldNotLoadMenu: "Could not load menu.",
    couldNotDeleteItem: "Could not delete item.",
    couldNotUpdateItem: "Could not update item.",
    qrCodeGenerator: "QR Code Generator",
    tableNumberOptional: "Table number (optional)",
    copied: "Copied!",
    copyLink: "Copy Link",
    download: "Download",
    print: "Print",
    generalMenu: "General Menu",
    scanNow: "Scan Now",
    addMenuItem: "Add Menu Item",
    fillInAllDetails: "Fill in all the details to publish this item",
    itemPhoto: "Item Photo",
    jpgPngWebp: "JPG, PNG, or WEBP",
    examplePhotoUrl: "https://example.com/photo.jpg",
    exampleClassicCheeseburger: "e.g. Classic Cheeseburger",
    usd: "USD",
    khr: "KHR",
    availableLabel: "AVAILABLE",
    vegLabel: "VEG",
    couldNotSaveMenuItem: "Could not save menu item.",
    createRestaurantLink: "Create restaurant →",
    // Orders
    orders: "Orders",
    searchOrders: "Search orders, items…",
    kitchen: "Kitchen",
    total: "Total",
    orderOverview: "Order Overview",
    ordersShown: "{count} order{plural} shown",
    shown: "shown",
    order: "Order",
    status: "Status",
    date: "Date",
    actions: "Actions",
    noItems: "No items",
    createRestaurantToViewOrders: "Create a restaurant to view orders.",
    loadingOrders: "Loading orders…",
    noOrdersFound: "No orders found.",
    orderDetails: "Order Details",
    customer: "Customer",
    guest: "Guest",
    table: "Table",
    takeaway: "Takeaway",
    orderTime: "Order Time",
    itemsCount: "Items Count",
    orderItems: "Order Items",
    qty: "Qty",
    unitPrice: "Unit Price",
    notes: "Notes",
    totalAmount: "Total Amount",
    close: "Close",
    printReceipt: "Print Receipt",
    couldNotLoadOrders: "Could not load orders.",
    couldNotUpdateOrder: "Could not update order.",
    couldNotDeleteOrder: "Could not delete order.",
    deleteOrderConfirm: "Delete this order?",

    // Dashboard
    dashboard: "Dashboard",
    totalSales: "Total Sales",
    totalOrders: "Total Orders",
    revenue: "Revenue",
    salesOverview: "Sales Overview",
    pendingOrders: "pending",
    totalOrdersLabel: "total orders",
    topSelling: "Top Selling",
    noOrderData: "No order data yet",
    sold: "sold",
    hourly: "Hourly",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    custom: "Custom",
    day: "Day",
    month: "Month",
    year: "Year",
    loadingChart: "Loading chart…",
    newOrder: "New Order!",
    signOut: "Sign Out",
    viewProfile: "View Profile",
    editProfile: "Edit Profile",
    noEmail: "No email",
    noPhone: "No phone",
    noAddress: "No address",
    createRestaurantProfile: "Create a restaurant profile to see live dashboard data.",
    pending: "Pending",
    accepted: "Accepted",
    completed: "Completed",
    cancelled: "Cancelled",
    noTablesAddedYet: "No tables added yet.",
    automaticallySwitchToViewOnly: `When enabled, the menu will automatically switch to "View Only" mode outside operating hours`,
    settings: "Settings",

    // Settings
    restaurantSettings: "Restaurant Settings",
    shopProfile: "Shop Profile",
    geofencing: "Geofencing",
    operatingHours: "Operating Hours",
    tableMapQR: "Table Map & QR",
    connectWithTelegram: "Connect with Telegram",
    receiveInvoicesTelegram: "Receive invoices via Telegram when orders are completed!",
    telegramChatId: "Telegram Chat ID",
    scanToStartChat: "Scan to start chat!",
    justStartChat: "Just start a chat with @scannowverification_bot and the bot will send you your Chat ID!",
    shopIdentity: "Shop Identity",
    thisIsHowYourCustomersSeeYourBrand: "This is how your customers see your brand.",
    placeName: "Place Name",
    phoneNumber: "Phone Number",
    addExtraNumber: "Add Extra Number",
    extraPhone: "Extra Phone",
    extraPhoneNumber: "Extra Phone",
    description: "Description",
    locationName: "Location Name",
    locationLink: "Location Link",
    exchangeRateUsdToKhr: "Exchange Rate (USD to KHR)",
    language: "Language",
    saveAllChanges: "Save All Changes",
    dangerZone: "Danger Zone",
    deletingYourAccountWillPermanentlyDeleteAllData: "Deleting your account will permanently delete all data.",
    deleteAccount: "Delete Account",
    deleteAccountConfirmPrompt: "Please type \"delete account\" to confirm.",
    deleteAccountPlaceholder: "delete account",
    deleteNow: "Delete Now",
    enableGeofencing: "Enable Geofencing",
    whenEnabledCustomersMustBeNearYourShopToPlaceOrders: "When enabled, customers must be near your shop to place orders.",
    shopLatitude: "Shop Latitude",
    shopLongitude: "Shop Longitude",
    allowedRadiusMeters: "Allowed Radius (Meters)",
    strict: "Strict",
    standard: "Standard",
    wide: "Wide",
    detectMyCurrentLocation: "Detect My Current Location",
    detecting: "Detecting…",
    autoCloseOrders: "Auto-Close Orders",
    automaticallyBlockOrderingOutsideYourShopOperatingHours: "Automatically block ordering outside your shop's operating hours.",
    openingTime: "Opening Time",
    closingTime: "Closing Time",
    tableMapQRBuilder: "Table Map & QR Builder",
    designYourRestaurantFloorPlanAndManageActiveTables: "Design your restaurant floor plan and manage active tables.",
    addTable: "Add Table",
    noteTableDragAndDropPositionSavingIsEnabled: "Note: Table drag-and-drop position saving is enabled.",
    qrCodeTable: "QR Code - Table",
    scanToOrderFromYourTable: "Scan to order from your table!",
    downloadQRCode: "Download QR Code",
    totalBill: "Total Bill",
    completeAndPrintInvoice: "Complete & Print Invoice",
    completeSession: "Complete Session",
    sessionCompletedAndBillCleared: "Session completed and bill cleared.",
    orderStatusUpdatedSuccessfully: "Order status updated successfully",
    archive: "Archive",

    // User Management
    userManagement: "User Management",
    manageRestaurantRoles: "Manage restaurant roles and team permissions.",
    addNewUser: "Add New User",
    totalTeam: "Total Team",
    managers: "Managers",
    kitchenStaff: "Kitchen Staff",
    searchByNameOrEmail: "Search by name or email...",
    ownerOnlyAccess: "Owner-only Access",
    user: "User",
    role: "Role",
    email: "Email",
    fetchingTeamMembers: "Fetching team members...",
    noUsersFound: "No users found.",
    addTeamMember: "Add Team Member",
    createNewAccount: "Create new account",
    fullName: "Full Name",
    egPreapSovath: "e.g. Preap Sovath",
    emailAddress: "Email Address",
    egStaffAtRestaurant: "preapsovath@gmail.com",
    temporaryPassword: "Temporary Password",
    min6Characters: "Min. 6 characters",
    roleAndPermissions: "Role & Permissions",
    staff: "Staff",
    createAccount: "Create Account",
    creatingAccount: "Creating Account...",
    userDetails: "User Details",
    viewAccountInformation: "View account information",
    lastLogin: "Last Login",
    nA: "N/A",
    active: "Active",
    editUser: "Edit User",
    updateAccountInformation: "Update account information",
    newPasswordOptional: "New Password (optional)",
    leaveBlankToKeepCurrent: "Leave blank to keep current",
    saveChanges: "Save Changes",
    savingChanges: "Saving Changes...",
    deleteUser: "Delete User?",
    thisActionCannotBeUndone: "This action cannot be undone.",
    failedToLoadUsers: "Failed to load users. Please ensure you have owner permissions.",
    failedToCreateUser: "Failed to create user.",
    failedToUpdateUser: "Failed to update user.",
    failedToDeleteUser: "Failed to delete user.",
    noRestaurantContext: "No restaurant context found.",
    owner: "Owner",
    
    // Other
    loading: "Loading…",
    error: "Error",
    okay: "Okay",
  },
  kh: {
    // Menu
    menu: "ម៉ឺនុយ",
    searchDishes: "ស្វែងរកមុខម្ហូប…",
    grid: "ក្រឡា",
    list: "បញ្ជី",
    qrCode: "QR Code",
    addDish: "បន្ថែមមុខម្ហូប",
    yourRestaurant: "ភោជនីយដ្ឋានរបស់អ្នក",
    view: "មើល",
    edit: "កែប្រែ",
    totalDishes: "មុខម្ហូបសរុប",
    available: "អាចកុម្មង់បាន",
    categories: "ប្រភេទមុខម្ហូប",
    all: "ទាំងអស់",
    createYourRestaurantProfile: "បង្កើតទំព័រផ្ទាល់ខ្លួនភោជនីយដ្ឋាន មុនពេលបន្ថែមមុខម្ហូប។",
    createRestaurant: "បង្កើតភោជនីយដ្ឋាន",
    noItemsFound: "មិនមានមុខម្ហូបទេ",
    items: "មុខម្ហូប",
    item: "មុខម្ហូប",
    unavailable: "មិនអាចរកបាន",
    photo: "រូបភាព",
    clickToUpload: "ចុចដើម្បីផ្ទុកឡើង",
    orPasteImageUrl: "ឬបិទភ្ជាប់តំណរូបភាព…",
    name: "ឈ្មោះ",
    dishName: "ឈ្មោះមុខម្ហូប",
    category: "ប្រភេទ",
    describeTheDish: "ពិពណ៌នាអំពីមុខម្ហូប…",
    pricing: "ការកំណត់តម្លៃ",
    auto: "ស្វ័យប្រវត្តិ",
    autoCalculateKhr: "គណនាប្រាក់៛ដោយស្វ័យប្រវត្តិ",
    rate: "អត្រា",
    options: "ជម្រើស",
    visibleOnMenu: "អាចមើលឃើញនៅលើម៉ឺនុយ",
    plantBasedItem: "មុខម្ហូបរបស់រុក្ខជាតិ",
    preview: "មើលជាមុន",
    itemName: "ឈ្មោះមុខម្ហូប…",
    noDescriptionYet: "មិនទាន់មានការពិពណ៌នានៅឡើយ…",
    saveItem: "រក្សាទុកមុខម្ហូប",
    saving: "កំពុងរក្សាទុក…",
    cancel: "បោះបង់",
    editItem: "កែប្រែមុខម្ហូប",
    chooseImage: "ជ្រើសរូបភាព",
    orPasteUrl: "ឬបិទភ្ជាប់តំណ",
    pleaseChooseAnImageFile: "សូមជ្រើសឯកសាររូបភាពមួយ។",
    couldNotLoadMenu: "មិនអាចផ្ទុកម៉ឺនុយបានទេ។",
    couldNotDeleteItem: "មិនអាចលុបមុខម្ហូបបានទេ។",
    couldNotUpdateItem: "មិនអាចបន្ទាន់សម្របស់ចោតមុខម្ហូបបានទេ។",
    qrCodeGenerator: "កម្មវិធីបង្កើត QR Code",
    tableNumberOptional: "លេខតុ (មិនចាំបាច់)",
    copied: "បានចម្លង!",
    copyLink: "ចម្លងតំណ",
    download: "ទាញយក",
    print: "បោះពុម្ព",
    generalMenu: "ម៉ឺនុយទូទៅ",
    scanNow: "ស្កេនឥឡូវនេះ",
    addMenuItem: "បន្ថែមមុខម្ហូប",
    fillInAllDetails: "បំពេញព័ត៌មានទាំងអស់ដើម្បីបោះពុម្ពមុខម្ហូបនេះ",
    itemPhoto: "រូបភាពមុខម្ហូប",
    jpgPngWebp: "JPG, PNG, ឬ WEBP",
    examplePhotoUrl: "https://example.com/photo.jpg",
    exampleClassicCheeseburger: "ឧទាហរណ៍៖ ឈីសប៊ឺហ្គឺរបុរាណ",
    usd: "USD",
    khr: "KHR",
    availableLabel: "អាចប្រើបាន",
    vegLabel: "បន្លែ",
    couldNotSaveMenuItem: "មិនអាចរក្សាទុកមុខម្ហូបបានទេ។",
    createRestaurantLink: "បង្កើតភោជនីយដ្ឋាន →",
    // Orders
    orders: "ការបញ្ជាទិញ",
    searchOrders: "ស្វែងរកការបញ្ជាទិញ",
    kitchen: "ផ្ទះបាយ",
    total: "សរុប",
    orderOverview: "ទិដ្ឋភាពទូទៅនៃការបញ្ជាទិញ",
    ordersShown: "{count} ការបញ្ជាទិញ{plural} ត្រូវបង្ហាញ",
    shown: "ត្រូវបង្ហាញ",
    order: "ការបញ្ជាទិញ",
    status: "ស្ថានភាព",
    date: "ថ្ងៃ",
    actions: "សកម្មភាព",
    noItems: "មិនមានមុខម្ហូប",
    createRestaurantToViewOrders: "បង្កើតភោជនីយដ្ឋានដើម្បីមើលការបញ្ជាទិញ។",
    loadingOrders: "កំពុងផ្ទុកការបញ្ជាទិញ…",
    noOrdersFound: "មិនមានការបញ្ជាទិញ។",
    orderDetails: "លម្អិតការបញ្ជាទិញ",
    customer: "អតិថិជន",
    guest: "ភ្ញៀវ",
    table: "តុ",
    takeaway: "យកទៅ",
    orderTime: "ពេលវេលាបញ្ជាទិញ",
    itemsCount: "ចំនួនមុខម្ហូប",
    orderItems: "មុខម្ហូបក្នុងការបញ្ជាទិញ",
    qty: "ចំនួន",
    unitPrice: "តម្លៃរាយ",
    notes: "កំណត់ចំណាំ",
    totalAmount: "ចំនួនទឹកប្រាក់សរុប",
    close: "បិទ",
    printReceipt: "បោះពុម្ពវិក្កយបត្រ",
    couldNotLoadOrders: "មិនអាចផ្ទុកការបញ្ជាទិញបានទេ។",
    couldNotUpdateOrder: "មិនអាចធ្វើបច្ចុប្បន្នភាពការបញ្ជាទិញបានទេ។",
    couldNotDeleteOrder: "មិនអាចលុបការបញ្ជាទិញបានទេ។",
    deleteOrderConfirm: "លុបការបញ្ជាទិញនេះ?",

    // Dashboard
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    totalSales: "ការលក់សរុប",
    totalOrders: "ការបញ្ជាទិញសរុប",
    revenue: "ប្រាក់ចំណូល",
    salesOverview: "ទិដ្ឋភាពទូទៅនៃការលក់",
    pendingOrders: "កំពុងរង់ចាំ",
    totalOrdersLabel: "ការបញ្ជាទិញសរុប",
    topSelling: "លក់ដាច់បំផុត",
    noOrderData: "មិនទាន់មានទិន្នន័យការបញ្ជាទិញនៅឡើយ។",
    sold: "បានលក់",
    hourly: "ម៉ោង",
    daily: "ថ្ងៃ",
    monthly: "ខែ",
    yearly: "ឆ្នាំ",
    custom: "ផ្ទាល់ខ្លួន",
    day: "ថ្ងៃ",
    month: "ខែ",
    year: "ឆ្នាំ",
    loadingChart: "កំពុងផ្ទុកតារាង…",
    newOrder: "ការបញ្ជាទិញថ្មី!",
    signOut: "ចាកចេញ",
    viewProfile: "មើលទំព័រផ្ទាល់ខ្លួន",
    editProfile: "កែប្រែទំព័រផ្ទាល់ខ្លួន",
    noEmail: "គ្មានអ៊ីមែល",
    noPhone: "គ្មានលេខទូរស័ព្ទ",
    noAddress: "គ្មានអាសយដ្ឋាន",
    createRestaurantProfile: "បង្កើតទំព័រផ្ទាល់ខ្លួនភោជនីយដ្ឋាន ដើម្បីមើលទិន្នន័យផ្ទាំងបញ្ជាផ្ទាល់ពេលវេលា។",
    pending: "កំពុងរង់ចាំ",
    accepted: "បានទទួល",
    completed: "រួចរាល់",
    cancelled: "បានលុបចោល",
    noTablesAddedYet: "មិនទាន់មានតុនៅឡើយទេ។",
    automaticallySwitchToViewOnly: `នៅពេលបើក ម៉ឺនុយនឹងប្តូរទៅរបៀប "មើលតែប៉ុណ្ណោះ" ដោយស្វ័យប្រវត្តិនៅម៉ោងមិនសមរម្យ`,
    settings: "ការកំណត់",

    // Settings
    restaurantSettings: "ការកំណត់ភោជនីយដ្ឋាន",
    shopProfile: "ព័ត៌មានហាង",
    geofencing: "កំណត់ទីតាំង",
    operatingHours: "ម៉ោងបើក និងបិទ",
    tableMapQR: "ផែនទីតុ និង QR",
    connectWithTelegram: "តភ្ជាប់ជាមួយ Telegram",
    receiveInvoicesTelegram: "ទទួលបានវិក្កយបត្រតាម Telegram នៅពេលអ្នកបញ្ជាទិញរួចរាល់!",
    telegramChatId: "Telegram Chat ID",
    scanToStartChat: "ស្កេនដើម្បីចាប់ផ្តើមជជែក!",
    justStartChat: "សូមចាប់ផ្តើមជជែកជាមួយ @scannowverification_bot ហើយ Bot នឹងផ្ញើ Chat ID របស់អ្នកមកឯង!",
    shopIdentity: "អត្តសញ្ញាណហាង",
    thisIsHowYourCustomersSeeYourBrand: "នេះជារបៀបដែលអតិថិជនរបស់អ្នកមើលឃើញម៉ាករបស់អ្នក។",
    placeName: "ឈ្មោះហាង",
    phoneNumber: "លេខទូរស័ព្ទ",
    addExtraNumber: "បន្ថែមលេខទូរស័ព្ទ",
    extraPhone: "លេខទូរស័ព្ទបន្ថែម",
    extraPhoneNumber: "លេខទូរស័ព្ទបន្ថែម",
    description: "ការពិពណ៌នា",
    locationName: "ឈ្មោះទីតាំង",
    locationLink: "តំណភ្ជាប់ទីតាំង",
    exchangeRateUsdToKhr: "អត្រាប្តូរប្រាក់ (USD ទៅ KHR)",
    language: "ភាសា",
    saveAllChanges: "រក្សាទុកការផ្លាស់ប្តូរទាំងអស់",
    dangerZone: "តំបន់គ្រោះថ្នាក់",
    deletingYourAccountWillPermanentlyDeleteAllData: "ការលុបគណនីរបស់អ្នកនឹងលុបទិន្នន័យទាំងអស់ជាអចិន្ត្រៃយ៍។",
    deleteAccount: "លុបគណនី",
    deleteAccountConfirmPrompt: "សូមវាយ \"លុបគណនី\" ដើម្បីបញ្ជាក់។",
    deleteAccountPlaceholder: "លុបគណនី",
    deleteNow: "លុបឥឡូវ",
    enableGeofencing: "បើកការកំណត់ Geofencing",
    whenEnabledCustomersMustBeNearYourShopToPlaceOrders: "នៅពេលបើក អតិថិជនត្រូវតែនៅជិតហាងរបស់អ្នកដើម្បីកម្ម៉ង់។",
    shopLatitude: "រយៈទទឹងហាង",
    shopLongitude: "រយៈបណ្តោយហាង",
    allowedRadiusMeters: "កាំដែលអនុញ្ញាត (ម៉ែត្រ)",
    strict: "តឹងរ៉ឹង",
    standard: "ស្តង់ដារ",
    wide: "ធំទូលាយ",
    detectMyCurrentLocation: "ស្វែងរកទីតាំងបច្ចុប្បន្នរបស់ខ្ញុំ",
    detecting: "កំពុងស្វែងរក…",
    autoCloseOrders: "បិទការកម្ម៉ង់ស្វ័យប្រវត្តិ",
    automaticallyBlockOrderingOutsideYourShopOperatingHours: "បិទការកម្ម៉ង់ដោយស្វ័យប្រវត្តិកាលណាដល់ម៉ោងបិទហាង។",
    openingTime: "ម៉ោងបើក",
    closingTime: "ម៉ោងបិទ",
    tableMapQRBuilder: "ផែនទីតុ និង អ្នកបង្កើត QR",
    designYourRestaurantFloorPlanAndManageActiveTables: "រៀបចំផែនការប្លង់តុ និងគ្រប់គ្រងតុដែលកំពុងដំណើរការ។",
    addTable: "បន្ថែមតុ",
    noteTableDragAndDropPositionSavingIsEnabled: "ចំណាំ៖ ការរក្សាទុកទីតាំងតុត្រូវបានបើក។",
    qrCodeTable: "QR Code - តុ",
    scanToOrderFromYourTable: "ស្កេនដើម្បីបញ្ជាទិញពីតុរបស់អ្នក!",
    downloadQRCode: "ទាញយក QR Code",
    totalBill: "វិក្កយបត្រសរុប",
    completeAndPrintInvoice: "បញ្ចប់ និង បោះពុម្ពវិក្កយបត្រ",
    completeSession: "បញ្ចប់មេរៀន",
    sessionCompletedAndBillCleared: "មេរៀនបានបញ្ចប់ និងវិក្កយបត្រត្រូវបានលុបចោល។",
    orderStatusUpdatedSuccessfully: "ស្ថានភាពការបញ្ជាទិញត្រូវបានបន្ទាន់សម្របស់ចោតជោគជ័យ។",
    archive: "ប្រវត្តិបញ្ជាទិញ",

    // User Management
    userManagement: "ការគ្រប់គ្រងអ្នកប្រើប្រាស់",
    manageRestaurantRoles: "គ្រប់គ្រងតួនាទីភោជនីយដ្ឋាន និងការអនុញ្ញាតរបស់ក្រុមការងារ។",
    addNewUser: "បន្ថែមអ្នកប្រើប្រាស់ថ្មី",
    totalTeam: "ក្រុមការងារទាំងមូល",
    managers: "អ្នកគ្រប់គ្រង",
    kitchenStaff: "បុគ្គលិកផ្ទះបាយ",
    searchByNameOrEmail: "ស្វែងរកតាមឈ្មោះ ឬអ៊ីមែល...",
    ownerOnlyAccess: "អាចចូលប្រើបានតែម្ចាស់ប៉ុណ្ណោះ",
    user: "អ្នកប្រើប្រាស់",
    role: "តួនាទី",
    email: "អ៊ីមែល",
    fetchingTeamMembers: "កំពុងទាញយកសមាជិកក្រុមការងារ...",
    noUsersFound: "មិនមានអ្នកប្រើប្រាស់ទេ។",
    addTeamMember: "បន្ថែមសមាជិកក្រុមការងារ",
    createNewAccount: "បង្កើតគណនីថ្មី",
    fullName: "ឈ្មោះពេញ",
    egPreapSovath: "ឧទាហរណ៍៖ ព្រាប សុវត្ថិ",
    emailAddress: "អាសយដ្ឋានអ៊ីមែល",
    egStaffAtRestaurant: "preapsovath@gmail.com",
    temporaryPassword: "ពាក្យសម្ងាត់បណ្តោះអាសន្ន",
    min6Characters: "អប្បបរមា 6 តួអក្សរ",
    roleAndPermissions: "តួនាទី និងការអនុញ្ញាត",
    staff: "បុគ្គលិក",
    createAccount: "បង្កើតគណនី",
    creatingAccount: "កំពុងបង្កើតគណនី...",
    userDetails: "ព័ត៌មានអ្នកប្រើប្រាស់",
    viewAccountInformation: "មើលព័ត៌មានគណនី",
    lastLogin: "ការចូលចុងក្រោយ",
    nA: "មិនមាន",
    active: "សកម្ម",
    editUser: "កែប្រែអ្នកប្រើប្រាស់",
    updateAccountInformation: "កែប្រែព័ត៌មានគណនី",
    newPasswordOptional: "ពាក្យសម្ងាត់ថ្មី (មិនចាំបាច់)",
    leaveBlankToKeepCurrent: "ទុកទទេដើម្បីរក្សាដូចដើម",
    saveChanges: "រក្សាទុកការផ្លាស់ប្តូរ",
    savingChanges: "កំពុងរក្សាទុកការផ្លាស់ប្តូរ...",
    deleteUser: "លុបអ្នកប្រើប្រាស់?",
    thisActionCannotBeUndone: "សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។",
    failedToLoadUsers: "មិនអាចផ្ទុកអ្នកប្រើប្រាស់បានទេ។ សូមប្រាកដថាអ្នកមានការអនុញ្ញាតជាម្ចាស់។",
    failedToCreateUser: "មិនអាចបង្កើតអ្នកប្រើប្រាស់បានទេ។",
    failedToUpdateUser: "មិនអាចធ្វើបច្ចុប្បន្នភាពអ្នកប្រើប្រាស់បានទេ។",
    failedToDeleteUser: "មិនអាចលុបអ្នកប្រើប្រាស់បានទេ។",
    noRestaurantContext: "មិនមានបរិបទភោជនីយដ្ឋានទេ។",
    owner: "ម្ចាស់",
    
    // Other
    loading: "កំពុងផ្ទុក…",
    error: "កំហុស",
    okay: "មិនអីទេ",
  },
};

type Language = "en" | "kh";
type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("scannow_language") as Language | null;
    if (savedLanguage && ["en", "kh"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("scannow_language", lang);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
